language: node_js
node_js:
- '0.10'
after_script:
# - CURR_BRANCH=git rev-parse --abbrev-ref HEAD
- git clone https://github.com/IrfanBaqui/travis
- cd travis
- TRAVIS_BRANCH
- TRAVIS_BUILD_DIR
- TRAVIS_COMMIT
- TRAVIS_PULL_REQUEST
- TRAVIS_REPO_SLUG
- git checkout master #should be latest release
- git checkout -b migration_test_branch_latest_release
- git rm -r migrations
- git branch -a
- git checkout remotes/origin/latest_release -- migrations
# - git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)
- cat .git/config
# - git checkout ${CURR_BRANCH} -- migrations
- npm install
- npm test
# - git clone -b test_branch --single-branch https://github.com/IrfanBaqui/travis
# after_script:
#   - git config credential.helper "store --file=.git/credentials"
#   - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
#   - node ./node_modules/grunt-cli/bin/grunt release
env:
  global:
    secure: silq5nWbDV2x8z1lWAMi4uaxye8JYhNx3PSbmTnMR3lDhl+cPsY1SNhFtK3v+JH6YsH/Oa+3UYud8K2iQzoI7ADMdH1LNLlB8nJ/XFYzC2tprRWVQyDdQcN6xrS1sWjTrYVBBprdzIezqbs9ck6nQmakf0WbJZyFdoJ+yLLRHpBJQ/RMGm0Xd1SIgNzyjh9DCanb4o/5NB96Y1MfJaptMTxftlYhkm1ipO64WT+fIFsSZztDqPd45yVLKQYVXBVqU64+GiiYIjvMdm0hZHUfAtC/MXd5a+Half4GLC+LCY5RzUmFlJL1rrOBH8gbnelqeSy2kBhOKcUK/jYQECf6JY3NpcUhmhiSDiGLE/z3CtQg5TmlXe53iMBcIRVf8ZRfwy+x0aEA7MUrxcR/GihorkBvH26brWdHNvdIToGmin/DcIolJMuAtbUlFtYg9qurceDWdnc/hjkOCZKe+l4+bdMlGyhe3kxtBYZiPYhncdJuMkETodHQnMOe/4AZ+uORFcRjDtyCzBAVcpeDvbeGV1H7bKEo5BXw8Cqi30flEcDaHucGNsjwbbdkvm1R5Gcz5I/7LHgELCNflXmG/XMP1aMTBDADZH/k8A6R/W9sdwd8wIrJUBknxPQWnNX6HT/8jwtNGIeFQlnFSFqNNAlbvZ2W/h0y0eD1Re4D83pPtPE=
